import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import ResponsivNav from "@/Components/Home/Navebar/ResponsivNav";
import Footer from "@/Components/Home/Footer/Footer";
import ScrollToTop from "@/Components/Helper/ScrollToTop";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const font = Space_Grotesk({
  weight : ['300','400','500','600','700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-learning Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <ResponsivNav />
        {children}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
